apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  namespace: game
  labels:
    auther: Tawfeeq
  annotation:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts: gameapp.com
      secretName: game-tls
  rules:
    - host: gameapp.com
      paths:
        path: /
        pathType: Prefix
        backend:
          name: game-service
          port:
            number: 80
