pipeline {
    agent {
        label 'my-agent'
    }
    environment{
        DOCKER_IMAGE = "tawfeeq421/game"
        DOCKER_TAG = "${BUILD_NUMBER}"
        SCANNER_HOME = tool 'sonar'
    }
    stages{
        stage('Clean Workspace'){
            steps{
                cleanWs()
            }
        }
        stage('Checkout SCM'){
            steps{
                git branch: 'main', url: 'https://github.com/tawfeeq421/react-game.git'
            }
        }
        stage('Install Dependency & Build'){
            parallel{
                stage('Install Dependency'){
                    steps{
                        sh 'npm install'
                    }
                }
                stage('Build Application'){
                    steps{
                        sh 'npm run build'
                    }
                }

            }
        }
        stage('SonarQube Scan & Quality Gate'){
            parallel{
                stage('SonarQube Scan'){
                    steps{
                        withSonarQubeEnv('sonarserver'){
                            sh"""
                            ${SCANNER_HOME}/bin/sonar-scanner \
                            -Dsonar.projectName=react-game \
                            -Dsonar.projectKey=react-game \
                            -Dsonar.sources=.
                            """
                        }
                    }
                }
                stage('Quality Gate'){
                    steps{
                        timeout(time: 1, unit: 'HOURS'){
                            waitForQualityGate abortPipeline: true
                        }
                    }
                }
            }
        }
        stage('Docker and Trivy'){
            parallel{
                stage('Trivy Scan FS'){
                    steps{
                        sh '''
                        trivy fs . \
                        --severity HIGH,CRITICAL \
                        --format table \
                        --no-progress \
                        -o trivy-report.txt || true
                        '''
                    }
                }
                stage('Docker Build'){
                    steps{
                        sh "docker build -t ${DOCKER_IMAGE}:${DOCKER_TAG} ."
                    }
                }
                stage('Trivy Image Scan'){
                    steps{
                        sh """
                        trivy image \
                        --severity HIGH,CRITICAL \
                        --no-progress \
                        --format table \
                        -o trivy-image-report.txt \
                        ${DOCKER_IMAGE}:${DOCKER_TAG} || true
                        """
                    }
                }
                stage('Docker Push'){
                    steps{
                        withCredentials([usernamePassword(
                            credentialsId: 'docker_cred',
                            usernaeVariable: 'USER',
                            passwordVariable: 'PASS'
                        )]){
                            sh '''
                            echo $PASS | docker login -u $USER --password-stdin

                            docker push ${DOCKER_IMAGE}:${DOCKER_TAG}

                            docker tag ${DOCKER_IMAGE}:${DOCKER_TAG} ${DOCKER_IMAGE}:latest
                            docker push ${DOCKER_IMAGE}:latest
                            '''
                        }
                    }
                }
                stage('Remove Unusage Image'){
                    steps{
                        sh " docker system prune -af && docker rm -f $(doker ps -a)"
                    }
                }
            }
        }
    }
    post{
        always{
            archiveArtifacts artifacts: 'trivy-report.txt', 'trivy-image-report.txt', fingerprint: true
        }
        success{
            slackSend(
                channel: "#amazon",
                color: "good",
                message: "✅ SUCCESS: ${env.JOB_NAME} #${BUILD_NUMBER}\nImage ${DOCKER_IMAGE}:${DOCKER_TAG}"
            )
        }
        failure{
            slackSend(
                channel: "#amazon",
                color: "danger",
                message: "❌ FAILURE: ${env.JOB_NAME} #${env.BUILD_NUMBER}\nCheck Logs ${env.BUILD_UR}"
            )
        }
    }
}
